-- Decouple app_users.id from auth.users(id).
--
-- Original schema made app_users.id a FK to auth.users(id), which creates a
-- chicken-and-egg problem for seeding: we want stable IFFL identities (so
-- teams.owner_id, contracts via teams, etc. all reference the same UUIDs)
-- before the 12 owners have ever signed in to create auth.users rows.
--
-- Fix: app_users.id becomes a plain UUID (deterministic, generated by the
-- seed importer via uuid_generate_v5). A new nullable column `auth_user_id`
-- references auth.users(id) and is filled the first time each owner signs in,
-- via email match in a post-signin trigger or app-side bootstrap.

-- 1. Drop the FK constraint (auto-created by `references auth.users(id)`)
alter table app_users
  drop constraint if exists app_users_id_fkey;

-- 2. Add the auth-link column
alter table app_users
  add column if not exists auth_user_id uuid unique
    references auth.users(id) on delete set null;

create index if not exists app_users_auth_user_id_idx
  on app_users(auth_user_id) where auth_user_id is not null;

-- 3. Update the auth_user_id() helper that RLS policies use, so it resolves
--    via the new column instead of relying on app_users.id == auth.uid().
create or replace function auth_user_id() returns uuid
language sql stable as $$ select auth.uid() $$;

-- The is_commissioner / is_treasurer / is_rules_committee / owns_team helpers
-- need to look up app_users by auth_user_id now (not id).
create or replace function is_commissioner() returns bool
language sql stable as $$
  select coalesce(
    (select is_commissioner from app_users where auth_user_id = auth.uid()),
    false
  )
$$;

create or replace function is_treasurer() returns bool
language sql stable as $$
  select coalesce(
    (select is_treasurer from app_users where auth_user_id = auth.uid()),
    false
  )
$$;

create or replace function is_rules_committee() returns bool
language sql stable as $$
  select coalesce(
    (select is_rules_committee from app_users where auth_user_id = auth.uid()),
    false
  )
$$;

create or replace function owns_team(p_team_id uuid) returns bool
language sql stable as $$
  select exists(
    select 1 from teams t
    join app_users u on u.id = t.owner_id
    where t.id = p_team_id and u.auth_user_id = auth.uid()
  )
$$;

-- 4. RLS policies that referenced `app_users.id = auth.uid()` directly need
--    to use auth_user_id now. The only one is app_users_self_update.
drop policy if exists app_users_self_update on app_users;
create policy app_users_self_update on app_users for update
  to authenticated
  using (auth_user_id = auth.uid())
  with check (auth_user_id = auth.uid());

drop policy if exists rule_proposals_self_insert on rule_proposals;
create policy rule_proposals_self_insert on rule_proposals for insert
  to authenticated
  with check (
    submitter_id in (select id from app_users where auth_user_id = auth.uid())
  );

drop policy if exists rule_votes_self_write on rule_votes;
create policy rule_votes_self_write on rule_votes for all
  to authenticated
  using (
    voter_id in (select id from app_users where auth_user_id = auth.uid())
  ) with check (
    voter_id in (select id from app_users where auth_user_id = auth.uid())
  );

drop policy if exists low_points_parlay_picks_self on low_points_parlay_picks;
create policy low_points_parlay_picks_self on low_points_parlay_picks for all
  to authenticated
  using (
    owner_id in (select id from app_users where auth_user_id = auth.uid())
  ) with check (
    owner_id in (select id from app_users where auth_user_id = auth.uid())
  );
