name: iOS Build & Upload
on:
  push:
    branches: [ main ]
jobs:
  build-ios:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - run: pod install
      - run: sudo xcode-select -switch /Applications/Xcode_15.app/Contents/Developer
      - name: Decode Export Options
        run: |
          echo -n "${{ secrets.EXPORT_OPTIONS_BASE64 }}" | base64 --decode -o $RUNNER_TEMP/ExportOptions.plist
      - name: Build and Archive
        run: |
          xcodebuild -workspace CodeRed.xcworkspace -scheme CodeRed -configuration Release -archivePath $RUNNER_TEMP/CodeRed.xcarchive archive
      - name: Export Archive
        run: |
          xcodebuild -exportArchive -archivePath $RUNNER_TEMP/CodeRed.xcarchive -exportOptionsPlist $RUNNER_TEMP/ExportOptions.plist -exportPath $RUNNER_TEMP/build -allowProvisioningUpdates
      - uses: maierj/fastlane-action@v1.4.0
        with:
          lane: ios upload_ios_beta_Testflight
        env:
          DEVELOPER_APP_ID: ${{ secrets.DEVELOPER_APP_ID }}
          DEVELOPER_APP_IDENTIFIER: ${{ secrets.DEVELOPER_APP_IDENTIFIER }}
          DEVELOPER_PORTAL_TEAM_ID: ${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}
          FASTLANE_APPLE_ID: ${{ secrets.FASTLANE_APPLE_ID }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          GIT_AUTHORIZATION: ${{ secrets.GIT_AUTHORIZATION }}
          PROVISIONING_PROFILE_SPECIFIER: ${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}
          ASC_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          ASC_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
          P12_DISTRIBUTION_CERTIFICATE_BASE64: ${{ secrets.P12_DISTRIBUTION_CERTIFICATE_BASE64 }}
          P12_DISTRIBUTION_CERTIFICATE_PASSWORD: ${{ secrets.P12_DISTRIBUTION_CERTIFICATE_PASSWORD }}
          DISTRIBUTION_PROVISIONING_PROFILE_BASE64: ${{ secrets.DISTRIBUTION_PROVISIONING_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          EXPORT_OPTIONS_BASE64: ${{ secrets.EXPORT_OPTIONS_BASE64 }}
